version: '3.4'

services:
  postgresql:
    container_name: postgresql
    image: ${DOCKER_REGISTRY-}postgres
    ports: 
      - "5433:5432"
    environment:
      POSTGRES_DB: "DB"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"

  sqlbundle:
   container_name: App
   image: ${DOCKER_REGISTRY-}sqlbundle
   ports: 
    - "8080:80"
    - "60443:443"
   environment:
     DBserver: "postgresql"
     DBport: "5432"
     DBname: "DB"
     DBuser: "postgres"
     DBPassword: "123" 
   build:
      context: .
      dockerfile: SqlBundle/Dockerfile
   depends_on:
      - postgresql