version: '3.4'

services:
  postgresql:
<<<<<<< HEAD
=======
    container_name: postgresql
>>>>>>> main-too
    image: ${DOCKER_REGISTRY-}postgres
    ports: 
      - "5433:5432"
    environment:
      POSTGRES_DB: "DB"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"

  sqlbundle:
<<<<<<< HEAD
   image: ${DOCKER_REGISTRY-}sqlbundle
   ports: 
    - "80:80"
=======
   container_name: App
   image: ${DOCKER_REGISTRY-}sqlbundle
   ports: 
    - "8080:80"
    - "60443:443"
>>>>>>> main-too
   environment:
     DBserver: "postgresql"
     DBport: "5432"
     DBname: "DB"
     DBuser: "postgres"
     DBPassword: "123" 
   build:
      context: .
      dockerfile: SqlBundle/Dockerfile
<<<<<<< HEAD

=======
   depends_on:
      - postgresql
>>>>>>> main-too
